services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - GLOBAL_LOG_LEVEL=DEBUG
    volumes:
      - open-webui-data:/app/backend/data
      - ./static:/app/build/static
    restart: unless-stopped
 
volumes:
  open-webui-data:
 